services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: chs_recruta
      POSTGRES_USER: chs
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD no arquivo .env}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U chs -d chs_recruta"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://chs:${POSTGRES_PASSWORD}@db:5432/chs_recruta
      APP_ENV: development
      SECURITY_SECRET_KEY: ${SECURITY_SECRET_KEY:?Defina SECURITY_SECRET_KEY no arquivo .env}
      DEMO_ADMIN_PASSWORD: ${DEMO_ADMIN_PASSWORD:?Defina DEMO_ADMIN_PASSWORD no arquivo .env}
      SEED_DEMO: "true"
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
